[build]
  command = "npm run build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PRIVATE_TARGET = "server"
  NODE_ENV = "production"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

# Handle redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Role = ["admin"]}

# All other routes go to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 